### PR TITLE
Process vault on startup

### PR DESCRIPTION
**Pull request by evilgeniuschronicles**
I think in your big code refactor a call got lost. Unindexed files were not getting processed at startup so I added a call to processVault() as the last line of onload()

### CODE REVIEW

**Comment by MohrJonas** [comment]
According to https://github.com/obsidianmd/obsidian-releases/pull/1053#issuecomment-1191844584, processVault() should be wrapped in a onLayoutReady rather than onLoad

**Comment by evilgeniuschronicles** [comment]
OK, I moved the call into onLayoutReady callback. Obsidian would probably flag that in the future. processVault() is way lighter than it used to be now that it is enqueueing the files rather than actually doing the work, but it makes more sense in the callback anyway. Thanks for the feedback.

**Comment by MohrJonas** [comment]
What is the point of https://github.com/evilgeniuschronicles/obsidian-ocr/blob/5651db12b388cf043fc8c7d91affe34c567e9f55/src/Main.ts#L77
Did you forget to remove it?

**Comment by evilgeniuschronicles** [comment]
Yikes, yes. I was too excited. I started that thinking it was analogous to onload() but when I found the callback you define on workspace I forgot to remove it. Sorry about that.

**Comment by MohrJonas** [comment]
No worries. Everybody makes errors 😁

**Pull request merged**
